# docker-compose.yml
version: '3'
services:
  smc-lab-hackathon:
    container_name: smc-lab-hackathon-container
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/workspace
    env_file:
    - .env
    ports:
      - 9999:9999
    command: "jupyter notebook --port 9999 --ip 0.0.0.0 --no-browser --allow-root"